pr: none
trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_BUILDKIT: 1

stages:
  - stage: tests
    dependsOn: prepare
    displayName: Build & Test
    jobs:
      - job: test
        displayName: 'Test'
        steps:
          - script: |
              docker-compose build
              docker-compose run --rm tests
            displayName: 'Build & Run Tests'

          - task: PublishTestResults@2
            displayName: 'Publish Test results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'build/logs/*.xml'
