pr: none
trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_BUILDKIT: 1

stages:
  - stage: php82
    displayName: PHP 8.2
    dependsOn: []
    jobs:
      - job: build
        displayName: 'Build & Test'
        steps:
          - script: docker-compose build tests82
            displayName: 'Build Docker image'

          - script: docker-compose run --rm tests82
            displayName: 'Run Tests'

  - stage: php83
    displayName: PHP 8.3
    dependsOn: []
    jobs:
      - job: build
        displayName: 'Build & Test'
        steps:
          - script: docker-compose build tests83
            displayName: 'Build Docker image'

          - script: docker-compose run --rm tests83
            displayName: 'Run Tests'
