version: "3"

x-tests: &tests
  volumes:
    - ./build/logs/:/code/build/logs/
  command: ['composer', 'ci']


services:
  tests82: &tests82
    <<: *tests
    build:
      context: .
      args:
        PHP_VERSION: "8.2"

  tests83: &tests83
    <<: *tests
    build:
      context: .
      args:
        PHP_VERSION: "8.3"

  tests-local:
    <<: *tests82
    volumes:
      - .:/code
