version: "3"

x-tests: &tests
  image: keboola/cors
  volumes:
    - ./build/logs/:/code/build/logs/
  command: ['composer', 'ci']


services:
  tests74: &tests74
    <<: *tests
    build:
      context: .
      args:
        PHP_VERSION: 7.4

  tests80: &tests80
    <<: *tests
    build:
      context: .
      args:
        PHP_VERSION: 8.0

  tests81: &tests81
    <<: *tests
    build:
      context: .
      args:
        PHP_VERSION: 8.1

  tests-local:
    <<: *tests80
    volumes:
      - .:/code
