version: "3"

x-tests: &tests
  command: ['bash', '-c', 'composer install && composer ci']
  working_dir: /code
  volumes:
    - .:/code

services:
  tests82: &tests82
    <<: *tests
    build:
      context: .
      args:
        PHP_VERSION: "8.2"

  tests83: &tests83
    <<: *tests
    build:
      context: .
      args:
        PHP_VERSION: "8.3"

  tests-local:
    <<: *tests82
